package jetbrains.mps.lang.quotation.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class Antiquotation_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor implements AbstractAntiquotation_BehaviorDescriptor {
  public Antiquotation_BehaviorDescriptor() {
  }

  public int virtual_getMetaLevelChange_201537367881074474(SNode thisNode) {
    return AbstractAntiquotation_Behavior.virtual_getMetaLevelChange_201537367881074474(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.quotation.structure.Antiquotation";
  }
}
