package jetbrains.mps.baseLanguageInternal.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.BaseMethodCall;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.StaticMethodDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExtractStaticMethod_CallExpression extends BaseMethodCall {
  public static final String concept = "jetbrains.mps.baseLanguageInternal.structure.ExtractStaticMethod_CallExpression";

  public ExtractStaticMethod_CallExpression(SNode node) {
    super(node);
  }

  public StaticMethodDeclaration getStaticMethodDeclaration() {
    return this.ensureAdapter(StaticMethodDeclaration.class, "baseMethodDeclaration", this.getBaseMethodDeclaration());
  }

  public void setStaticMethodDeclaration(StaticMethodDeclaration node) {
    this.setBaseMethodDeclaration(node);
  }

  public static ExtractStaticMethod_CallExpression newInstance(SModel sm, boolean init) {
    return (ExtractStaticMethod_CallExpression) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguageInternal.structure.ExtractStaticMethod_CallExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExtractStaticMethod_CallExpression newInstance(SModel sm) {
    return ExtractStaticMethod_CallExpression.newInstance(sm, false);
  }
}
