package jetbrains.mps.bash.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ExternalCommandDeclaration_Constraints extends BaseConstraintsDescriptor {
  public ExternalCommandDeclaration_Constraints() {
    super("jetbrains.mps.bash.structure.ExternalCommandDeclaration");
  }
}
