package jetbrains.mps.lang.smodel.behavior;

/*Generated by MPS */


public class Node_InsertPrevSiblingOperation_BehaviorDescriptor extends SNodeOperation_BehaviorDescriptor {
  public Node_InsertPrevSiblingOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.smodel.structure.Node_InsertPrevSiblingOperation";
  }
}
