package jetbrains.mps.lang.smodel.behavior;

/*Generated by MPS */


public class Node_GetReferenceOperation_BehaviorDescriptor extends SNodeOperation_BehaviorDescriptor {
  public Node_GetReferenceOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.smodel.structure.Node_GetReferenceOperation";
  }
}
