package jetbrains.mps.lang.smodel.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PropertyRefQualifier_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPropertyAccessQualifier_BehaviorDescriptor {
  public PropertyRefQualifier_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.smodel.structure.PropertyRefQualifier";
  }
}
