package jetbrains.mps.bash.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StickyBitConditionalExpression extends UnaryConditionalExpression {
  public static final String concept = "jetbrains.mps.bash.structure.StickyBitConditionalExpression";

  public StickyBitConditionalExpression(SNode node) {
    super(node);
  }

  public static StickyBitConditionalExpression newInstance(SModel sm, boolean init) {
    return (StickyBitConditionalExpression) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.bash.structure.StickyBitConditionalExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StickyBitConditionalExpression newInstance(SModel sm) {
    return StickyBitConditionalExpression.newInstance(sm, false);
  }
}
