package jetbrains.mps.lang.traceable.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface UnitConcept_BehaviorDescriptor {
  public String virtual_getUnitName_5067982036267369911(SNode thisNode);
}
