package jetbrains.mpslite.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Map;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class FeatureAccessConcept_Behavior {
  private static Class[] PARAMETERS_8405639817129357299 = {SNode.class, SNode.class, Map.class, Map.class};
  private static Class[] PARAMETERS_8405639817129358591 = {SNode.class, Map.class, Map.class};

  public static void init(SNode thisNode) {
  }

  public static void virtual_fillConcept_1239891562930(SNode thisNode, SNode concept, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    throw new UnsupportedOperationException();
  }

  public static SNode virtual_createEditor_1239890004879(SNode thisNode, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    throw new UnsupportedOperationException();
  }

  public static void call_fillConcept_8405639817129357299(SNode thisNode, SNode concept, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mpslite.structure.FeatureAccessConcept"), "virtual_fillConcept_1239891562930", PARAMETERS_8405639817129357299, concept, conceptsToTargets, partsToLinks);
  }

  public static SNode call_createEditor_8405639817129358591(SNode thisNode, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mpslite.structure.FeatureAccessConcept"), "virtual_createEditor_1239890004879", PARAMETERS_8405639817129358591, conceptsToTargets, partsToLinks);
  }

  public static void callSuper_fillConcept_8405639817129357299(SNode thisNode, String callerConceptFqName, SNode concept, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mpslite.structure.FeatureAccessConcept"), callerConceptFqName, "virtual_fillConcept_1239891562930", PARAMETERS_8405639817129357299, concept, conceptsToTargets, partsToLinks);
  }

  public static SNode callSuper_createEditor_8405639817129358591(SNode thisNode, String callerConceptFqName, Map<SNode, SNode> conceptsToTargets, Map<SNode, SNode> partsToLinks) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mpslite.structure.FeatureAccessConcept"), callerConceptFqName, "virtual_createEditor_1239890004879", PARAMETERS_8405639817129358591, conceptsToTargets, partsToLinks);
  }
}
