package jetbrains.mps.execution.commands.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReportExecutionError extends ReportErrorStatement {
  public static final String concept = "jetbrains.mps.execution.commands.structure.ReportExecutionError";

  public ReportExecutionError(SNode node) {
    super(node);
  }

  public static ReportExecutionError newInstance(SModel sm, boolean init) {
    return (ReportExecutionError) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.execution.commands.structure.ReportExecutionError", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReportExecutionError newInstance(SModel sm) {
    return ReportExecutionError.newInstance(sm, false);
  }
}
