package jetbrains.mps.baseLanguage.util.plugin.refactorings;

/*Generated by MPS */

import jetbrains.mps.ide.dialogs.BaseDialog;
import javax.swing.JPanel;
import java.awt.Frame;
import java.awt.GridLayout;
import javax.swing.JTextArea;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import com.intellij.ui.ScrollPaneFactory;
import javax.swing.ScrollPaneConstants;
import javax.swing.JComponent;
import jetbrains.mps.ide.dialogs.DialogDimensionsSettings;

public class ProblemsDialog extends BaseDialog {
  private JPanel myPanel;
  private InlineMethodDialogModel myModel;

  public ProblemsDialog(Frame frame, String errors, InlineMethodDialogModel model) {
    super(frame, "Problems detected");
    this.myModel = model;
    this.myPanel = new JPanel(new GridLayout(1, 1));
    JTextArea area = new JTextArea("Following problems were found:\n" + errors);
    area.setEditable(false);
    area.setBackground(Color.WHITE);
    area.setLineWrap(true);
    this.myPanel.setBorder(new EmptyBorder(3, 3, 3, 3));
    this.myPanel.add(ScrollPaneFactory.createScrollPane(area, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER));
  }

  protected JComponent getMainComponent() {
    return this.myPanel;
  }

  @BaseDialog.Button(position = 0, name = "Ignore", mnemonic = 'I', defaultButton = true)
  public void onIgnore() {
    this.dispose();
    this.myModel.ignore();
  }

  @BaseDialog.Button(position = 1, name = "Cancel", mnemonic = 'C', defaultButton = false)
  public void onCancel() {
    this.dispose();
  }

  public DialogDimensionsSettings.DialogDimensions getDefaultDimensionSettings() {
    return new DialogDimensionsSettings.DialogDimensions(100, 200, 400, 300);
  }
}
