package jetbrains.mps.lang.generator.generationContext.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public abstract class GenerationContextOp_PatternRef_BehaviorDescriptor extends GenerationContextOp_Base_BehaviorDescriptor {
  public GenerationContextOp_PatternRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.generator.generationContext.structure.GenerationContextOp_PatternRef";
  }

  public abstract SNode virtual_getTarget_1758784108620114792(SNode thisNode);

  public abstract void virtual_setTarget_1758784108620254533(SNode thisNode, SNode target);
}
