package jetbrains.mps.xmlQuery.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class XMLSAXChildHandler extends XMLSAXHandlerFunction {
  public static final String concept = "jetbrains.mps.xmlQuery.structure.XMLSAXChildHandler";

  public XMLSAXChildHandler(SNode node) {
    super(node);
  }

  public static XMLSAXChildHandler newInstance(SModel sm, boolean init) {
    return (XMLSAXChildHandler) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.xmlQuery.structure.XMLSAXChildHandler", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static XMLSAXChildHandler newInstance(SModel sm) {
    return XMLSAXChildHandler.newInstance(sm, false);
  }
}
