package jetbrains.mps.xmlQuery.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class XMLSAXAttributeRule extends BaseConcept implements INamedConcept {
  public static final String concept = "jetbrains.mps.xmlQuery.structure.XMLSAXAttributeRule";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String IS_REQUIRED = "isRequired";
  public static final String HANDLER = "handler";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public XMLSAXAttributeRule(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(XMLSAXAttributeRule.NAME);
  }

  public void setName(String value) {
    this.setProperty(XMLSAXAttributeRule.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(XMLSAXAttributeRule.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(XMLSAXAttributeRule.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(XMLSAXAttributeRule.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(XMLSAXAttributeRule.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(XMLSAXAttributeRule.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(XMLSAXAttributeRule.VIRTUAL_PACKAGE, value);
  }

  public boolean getIsRequired() {
    return this.getBooleanProperty(XMLSAXAttributeRule.IS_REQUIRED);
  }

  public void setIsRequired(boolean value) {
    this.setBooleanProperty(XMLSAXAttributeRule.IS_REQUIRED, value);
  }

  public XMLSAXAttributeHandler getHandler() {
    return (XMLSAXAttributeHandler) this.getChild(XMLSAXAttributeHandler.class, XMLSAXAttributeRule.HANDLER);
  }

  public void setHandler(XMLSAXAttributeHandler node) {
    super.setChild(XMLSAXAttributeRule.HANDLER, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(XMLSAXAttributeRule.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, XMLSAXAttributeRule.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, XMLSAXAttributeRule.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(XMLSAXAttributeRule.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, XMLSAXAttributeRule.SMODEL_ATTRIBUTE, node);
  }

  public static XMLSAXAttributeRule newInstance(SModel sm, boolean init) {
    return (XMLSAXAttributeRule) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.xmlQuery.structure.XMLSAXAttributeRule", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static XMLSAXAttributeRule newInstance(SModel sm) {
    return XMLSAXAttributeRule.newInstance(sm, false);
  }
}
