package jetbrains.mps.lang.project.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import org.apache.commons.lang.StringUtils;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class MappingConfigNormalRef_Behavior {
  private static Class[] PARAMETERS_2721285250110400383 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isComplete_2721285250110257005(SNode thisNode) {
    if (StringUtils.isEmpty(SPropertyOperations.getString(thisNode, "modelUID"))) {
      return false;
    }
    if (SPropertyOperations.getString(thisNode, "modelUID").equals("*")) {
      return true;
    }
    if (StringUtils.isEmpty(SPropertyOperations.getString(thisNode, "nodeID"))) {
      return false;
    }
    return true;
  }

  public static boolean call_isComplete_2721285250110400383(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (Boolean) descriptor.invoke(Boolean.class, SNodeOperations.cast(thisNode, "jetbrains.mps.lang.project.structure.MappingConfigNormalRef"), "virtual_isComplete_2721285250110257005", PARAMETERS_2721285250110400383);
  }

  public static boolean callSuper_isComplete_2721285250110400383(SNode thisNode, String callerConceptFqName) {
    return (Boolean) BehaviorManager.getInstance().invokeSuper(Boolean.class, SNodeOperations.cast(thisNode, "jetbrains.mps.lang.project.structure.MappingConfigNormalRef"), callerConceptFqName, "virtual_isComplete_2721285250110257005", PARAMETERS_2721285250110400383);
  }
}
