package jetbrains.mps.lang.refactoring.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class UpdateModelClause_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public UpdateModelClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.refactoring.structure.UpdateModelClause";
  }
}
