package jetbrains.mps.baseLanguage.builders.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class SimpleBuilderDeclaration_BehaviorDescriptor extends BaseSimpleBuilderDeclaration_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public SimpleBuilderDeclaration_BehaviorDescriptor() {
  }

  public SNode virtual_getContextDeclaration_6254726786820551255(SNode thisNode) {
    return SimpleBuilderDeclaration_Behavior.virtual_getContextDeclaration_6254726786820551255(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.builders.structure.SimpleBuilderDeclaration";
  }
}
