package jetbrains.mps.baseLanguage.constructors.behavior;

/*Generated by MPS */


public class CustomArgumentClause_BehaviorDescriptor extends ArgumentClause_BehaviorDescriptor {
  public CustomArgumentClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.constructors.structure.CustomArgumentClause";
  }
}
