package jetbrains.mps.lang.editor.table.structure;

/*Generated by MPS */

import jetbrains.mps.lang.editor.structure.EditorCellModel;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.structure.structure.LinkDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CellModel_HierarchycalTable extends EditorCellModel {
  public static final String concept = "jetbrains.mps.lang.editor.table.structure.CellModel_HierarchycalTable";
  public static final String MY_PROP = "myProp";
  public static final String HEADER_ROW_LINK_DECLARATION = "headerRowLinkDeclaration";
  public static final String ROWS_LINK_DECLARATION = "rowsLinkDeclaration";
  public static final String CELLS_IN_ROW_LINK_DECLARATION = "cellsInRowLinkDeclaration";

  public CellModel_HierarchycalTable(SNode node) {
    super(node);
  }

  public String getMyProp() {
    return this.getProperty(CellModel_HierarchycalTable.MY_PROP);
  }

  public void setMyProp(String value) {
    this.setProperty(CellModel_HierarchycalTable.MY_PROP, value);
  }

  public LinkDeclaration getHeaderRowLinkDeclaration() {
    return (LinkDeclaration) this.getReferent(LinkDeclaration.class, CellModel_HierarchycalTable.HEADER_ROW_LINK_DECLARATION);
  }

  public void setHeaderRowLinkDeclaration(LinkDeclaration node) {
    super.setReferent(CellModel_HierarchycalTable.HEADER_ROW_LINK_DECLARATION, node);
  }

  public LinkDeclaration getRowsLinkDeclaration() {
    return (LinkDeclaration) this.getReferent(LinkDeclaration.class, CellModel_HierarchycalTable.ROWS_LINK_DECLARATION);
  }

  public void setRowsLinkDeclaration(LinkDeclaration node) {
    super.setReferent(CellModel_HierarchycalTable.ROWS_LINK_DECLARATION, node);
  }

  public LinkDeclaration getCellsInRowLinkDeclaration() {
    return (LinkDeclaration) this.getReferent(LinkDeclaration.class, CellModel_HierarchycalTable.CELLS_IN_ROW_LINK_DECLARATION);
  }

  public void setCellsInRowLinkDeclaration(LinkDeclaration node) {
    super.setReferent(CellModel_HierarchycalTable.CELLS_IN_ROW_LINK_DECLARATION, node);
  }

  public static CellModel_HierarchycalTable newInstance(SModel sm, boolean init) {
    return (CellModel_HierarchycalTable) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.lang.editor.table.structure.CellModel_HierarchycalTable", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CellModel_HierarchycalTable newInstance(SModel sm) {
    return CellModel_HierarchycalTable.newInstance(sm, false);
  }
}
