package jetbrains.mps.baseLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IStatementListContainer extends INodeAdapter {
  public static final String concept = "jetbrains.mps.baseLanguage.structure.IStatementListContainer";
}
