package jetbrains.mps.lang.intentions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface ChildFilterBlock extends INodeAdapter {
  public static final String concept = "jetbrains.mps.lang.intentions.structure.ChildFilterBlock";
}
