package jetbrains.mps.baseLanguage.math.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class BigSumExpression extends ArithmSymbol {
  public static final String concept = "jetbrains.mps.baseLanguage.math.structure.BigSumExpression";

  public BigSumExpression(SNode node) {
    super(node);
  }

  public static BigSumExpression newInstance(SModel sm, boolean init) {
    return (BigSumExpression) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.math.structure.BigSumExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static BigSumExpression newInstance(SModel sm) {
    return BigSumExpression.newInstance(sm, false);
  }
}
