package jetbrains.mps.baseLanguage.math.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IntervalType extends Type {
  public static final String concept = "jetbrains.mps.baseLanguage.math.structure.IntervalType";
  public static final String ELEMENT_TYPE = "elementType";

  public IntervalType(SNode node) {
    super(node);
  }

  public Type getElementType() {
    return (Type) this.getChild(Type.class, IntervalType.ELEMENT_TYPE);
  }

  public void setElementType(Type node) {
    super.setChild(IntervalType.ELEMENT_TYPE, node);
  }

  public static IntervalType newInstance(SModel sm, boolean init) {
    return (IntervalType) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.math.structure.IntervalType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IntervalType newInstance(SModel sm) {
    return IntervalType.newInstance(sm, false);
  }
}
