package jetbrains.mps.lang.generator.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum GeneratorMessageType {
  info("info", "info"),
  warning("warning", "warning"),
  error("error", "error");

  private String myName;
  private String myValue;

  GeneratorMessageType(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

  public static List<GeneratorMessageType> getConstants() {
    List<GeneratorMessageType> list = ListSequence.fromList(new LinkedList<GeneratorMessageType>());
    ListSequence.fromList(list).addElement(GeneratorMessageType.info);
    ListSequence.fromList(list).addElement(GeneratorMessageType.warning);
    ListSequence.fromList(list).addElement(GeneratorMessageType.error);
    return list;
  }

  public static GeneratorMessageType getDefault() {
    return GeneratorMessageType.info;
  }

  public static GeneratorMessageType parseValue(String value) {
    if (value == null) {
      return GeneratorMessageType.getDefault();
    }
    if (value.equals(GeneratorMessageType.info.getValueAsString())) {
      return GeneratorMessageType.info;
    }
    if (value.equals(GeneratorMessageType.warning.getValueAsString())) {
      return GeneratorMessageType.warning;
    }
    if (value.equals(GeneratorMessageType.error.getValueAsString())) {
      return GeneratorMessageType.error;
    }
    return GeneratorMessageType.getDefault();
  }
}
