package jetbrains.mps.xmlSchema.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Set;

public class GroupReference_BehaviorDescriptor extends TypeExpression_BehaviorDescriptor {
  public GroupReference_BehaviorDescriptor() {
  }

  public void virtual_checkElements_1213877382378(SNode thisNode, Set<SNode> elementDeclarations) {
    GroupReference_Behavior.virtual_checkElements_1213877382378(thisNode, elementDeclarations);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.xmlSchema.structure.GroupReference";
  }
}
