package jetbrains.mps.ui.internal.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;
import jetbrains.mps.ui.modeling.behavior.IPartiallyDefinedStub_BehaviorDescriptor;

public class TypeStub_BehaviorDescriptor extends Type_BehaviorDescriptor implements IPartiallyDefinedStub_BehaviorDescriptor {
  public TypeStub_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.ui.internal.structure.TypeStub";
  }
}
