package jetbrains.mps.execution.settings.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import org.jetbrains.annotations.NonNls;
import jetbrains.mps.execution.common.behavior.IGeneratedToClass_Behavior;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.baseLanguage.classifiers.behavior.IClassifier_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baseLanguage.classifiers.behavior.IMember_Behavior;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PersistentConfiguration_Behavior {
  private static Class[] PARAMETERS_946964771156066501 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  @NonNls
  public static String virtual_getSuffix_946964771156905483(SNode thisNode) {
    return "Configuration";
  }

  public static String call_getGeneratedEditorName_946964771156066479(SNode thisNode) {
    return IGeneratedToClass_Behavior.call_getGeneratedClassName_946964771156905488(thisNode) + "_" + PersistentConfiguration_Behavior.call_getEditorSuffix_946964771156066551(thisNode);
  }

  public static String call_getFullEditorName_946964771156066491(SNode thisNode) {
    return IGeneratedToClass_Behavior.call_getFullName_946964771156905503(thisNode) + "_" + PersistentConfiguration_Behavior.call_getEditorSuffix_946964771156066551(thisNode);
  }

  public static SNode virtual_createType_1213877527970(SNode thisNode) {
    return new PersistentConfiguration_Behavior.QuotationClass_4ves9l_a0a0e().createNode(thisNode);
  }

  public static List<SNode> call_getTemplateProperties_946964771156066510(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "persistentProperty", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return PersistentPropertyDeclaration_Behavior.call_isTemplate_946964771156066860(it);
      }
    }).toListSequence();
  }

  public static List<SNode> call_getNonTemplateProperties_946964771156066530(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "persistentProperty", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(PersistentPropertyDeclaration_Behavior.call_isTemplate_946964771156066860(it));
      }
    }).toListSequence();
  }

  public static String call_getEditorSuffix_946964771156066551(SNode thisNode) {
    return "Editor";
  }

  public static List<SNode> virtual_getMembers_1213877528020(SNode thisNode, SNode contextNode) {
    List<SNode> allMemebers = IClassifier_Behavior.callSuper_getMembers_1213877528020(thisNode, "jetbrains.mps.execution.settings.structure.PersistentConfiguration", contextNode);
    if ((SNodeOperations.getAncestor(contextNode, "jetbrains.mps.execution.settings.structure.SettingsEditor", false, false) != null)) {
      return ListSequence.fromList(allMemebers).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return !(SNodeOperations.isInstanceOf(it, "jetbrains.mps.execution.settings.structure.PersistentConfigurationMethod")) || !(SNodeOperations.isInstanceOf(IMember_Behavior.call_getVisiblity_1213877352965(it), "jetbrains.mps.baseLanguage.structure.PrivateVisibility"));
        }
      }).toListSequence();
    }
    return allMemebers;
  }

  public static SNode call_createType_946964771156066501(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.execution.settings.structure.PersistentConfiguration"), "virtual_createType_1213877527970", PARAMETERS_946964771156066501);
  }

  public static SNode callSuper_createType_946964771156066501(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.execution.settings.structure.PersistentConfiguration"), callerConceptFqName, "virtual_createType_1213877527970", PARAMETERS_946964771156066501);
  }

  public static SNode getContextPersistentConfigurationType_946964771156066389(SNode node) {
    SNode configuration = SNodeOperations.getAncestor(node, "jetbrains.mps.execution.settings.structure.PersistentConfiguration", false, false);
    if (configuration == null) {
      SNode executor = SNodeOperations.getAncestor(node, "jetbrains.mps.execution.settings.structure.PersistentConfigurationAssistent", false, false);
      if (executor != null) {
        configuration = SLinkOperations.getTarget(executor, "configuration", false);
      }
    }
    return new PersistentConfiguration_Behavior.QuotationClass_4ves9l_a0c0l().createNode(configuration);
  }

  public static List<SNode> getContextPersistentProperties_946964771156066434(SNode node) {
    SNode configurationType = PersistentConfiguration_Behavior.getContextPersistentConfigurationType_946964771156066389(node);
    if ((configurationType == null) || (SLinkOperations.getTarget(configurationType, "persistentConfiguration", false) == null)) {
      return new ArrayList<SNode>();
    }
    return SLinkOperations.getTargets(SLinkOperations.getTarget(configurationType, "persistentConfiguration", false), "persistentProperty", true);
  }

  public static String getCheckMethodName_946964771156066466() {
    return "checkConfiguration";
  }

  public static class QuotationClass_4ves9l_a0a0e {
    public QuotationClass_4ves9l_a0a0e() {
    }

    public SNode createNode(Object parameter_3) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.execution.settings.structure.PersistentConfigurationType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        quotedNode1_2.setReferent("persistentConfiguration", (SNode) parameter_3);
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_4ves9l_a0c0l {
    public QuotationClass_4ves9l_a0c0l() {
    }

    public SNode createNode(Object parameter_3) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.execution.settings.structure.PersistentConfigurationType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        quotedNode1_2.setReferent("persistentConfiguration", (SNode) parameter_3);
        result = quotedNode1_2;
      }
      return result;
    }
  }
}
