package jetbrains.mps.lang.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.ConceptFunctionParameter;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OnModelsGeneratedBlock_success extends ConceptFunctionParameter {
  public static final String concept = "jetbrains.mps.lang.plugin.structure.OnModelsGeneratedBlock_success";

  public OnModelsGeneratedBlock_success(SNode node) {
    super(node);
  }

  public static OnModelsGeneratedBlock_success newInstance(SModel sm, boolean init) {
    return (OnModelsGeneratedBlock_success) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.lang.plugin.structure.OnModelsGeneratedBlock_success", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OnModelsGeneratedBlock_success newInstance(SModel sm) {
    return OnModelsGeneratedBlock_success.newInstance(sm, false);
  }
}
