package jetbrains.mps.lang.plugin.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UniversalRunConfigCreator extends BaseConcept implements INamedConcept {
  public static final String concept = "jetbrains.mps.lang.plugin.structure.UniversalRunConfigCreator";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String RC_TYPE = "rcType";
  public static final String TARGET = "target";
  public static final String CREATE_BLOCK = "createBlock";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public UniversalRunConfigCreator(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(UniversalRunConfigCreator.NAME);
  }

  public void setName(String value) {
    this.setProperty(UniversalRunConfigCreator.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(UniversalRunConfigCreator.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(UniversalRunConfigCreator.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(UniversalRunConfigCreator.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(UniversalRunConfigCreator.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(UniversalRunConfigCreator.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(UniversalRunConfigCreator.VIRTUAL_PACKAGE, value);
  }

  public RunConfigurationTypeDeclaration getRcType() {
    return (RunConfigurationTypeDeclaration) this.getReferent(RunConfigurationTypeDeclaration.class, UniversalRunConfigCreator.RC_TYPE);
  }

  public void setRcType(RunConfigurationTypeDeclaration node) {
    super.setReferent(UniversalRunConfigCreator.RC_TYPE, node);
  }

  public BaseCreatorTarget getTarget() {
    return (BaseCreatorTarget) this.getChild(BaseCreatorTarget.class, UniversalRunConfigCreator.TARGET);
  }

  public void setTarget(BaseCreatorTarget node) {
    super.setChild(UniversalRunConfigCreator.TARGET, node);
  }

  public CreateRunConfigBlock getCreateBlock() {
    return (CreateRunConfigBlock) this.getChild(CreateRunConfigBlock.class, UniversalRunConfigCreator.CREATE_BLOCK);
  }

  public void setCreateBlock(CreateRunConfigBlock node) {
    super.setChild(UniversalRunConfigCreator.CREATE_BLOCK, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(UniversalRunConfigCreator.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, UniversalRunConfigCreator.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, UniversalRunConfigCreator.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(UniversalRunConfigCreator.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, UniversalRunConfigCreator.SMODEL_ATTRIBUTE, node);
  }

  public static UniversalRunConfigCreator newInstance(SModel sm, boolean init) {
    return (UniversalRunConfigCreator) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.lang.plugin.structure.UniversalRunConfigCreator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UniversalRunConfigCreator newInstance(SModel sm) {
    return UniversalRunConfigCreator.newInstance(sm, false);
  }
}
