package jetbrains.mps.bash.behavior;

/*Generated by MPS */


public class AssingmentExpression_BehaviorDescriptor extends BaseAssingmentExpression_BehaviorDescriptor {
  public AssingmentExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.bash.structure.AssingmentExpression";
  }
}
