package jetbrains.mps.bash.behavior;

/*Generated by MPS */


public class EqualityExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public EqualityExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.bash.structure.EqualityExpression";
  }
}
