package jetbrains.mps.bash.behavior;

/*Generated by MPS */


public class MinusAssingmentExpression_BehaviorDescriptor extends BaseAssingmentExpression_BehaviorDescriptor {
  public MinusAssingmentExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.bash.structure.MinusAssingmentExpression";
  }
}
