package jetbrains.mps.bash.behavior;

/*Generated by MPS */


public class SemicolonTerminator_BehaviorDescriptor extends CommandTerminator_BehaviorDescriptor {
  public SemicolonTerminator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.bash.structure.SemicolonTerminator";
  }
}
