package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class CellModel_Error_BehaviorDescriptor extends CellModel_AbstractLabel_BehaviorDescriptor {
  public CellModel_Error_BehaviorDescriptor() {
  }

  public String virtual_getOpeningText_1220339714057(SNode thisNode) {
    return CellModel_Error_Behavior.virtual_getOpeningText_1220339714057(thisNode);
  }

  public String virtual_getClosingText_1220339738643(SNode thisNode) {
    return CellModel_Error_Behavior.virtual_getClosingText_1220339738643(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.CellModel_Error";
  }
}
