package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class CellMenuPart_AbstractGroup_Query_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public CellMenuPart_AbstractGroup_Query_BehaviorDescriptor() {
  }

  public SNode virtual_getExpectedReturnType_1213877374441(SNode thisNode) {
    return CellMenuPart_AbstractGroup_Query_Behavior.virtual_getExpectedReturnType_1213877374441(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.CellMenuPart_AbstractGroup_Query";
  }
}
