package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class CellLayout_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CellLayout_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.CellLayout";
  }
}
