package jetbrains.mps.lang.actions.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.ConceptFunctionParameter;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConceptFunctionParameter_nodeToCopyPreProcess extends ConceptFunctionParameter {
  public static final String concept = "jetbrains.mps.lang.actions.structure.ConceptFunctionParameter_nodeToCopyPreProcess";

  public ConceptFunctionParameter_nodeToCopyPreProcess(SNode node) {
    super(node);
  }

  public static ConceptFunctionParameter_nodeToCopyPreProcess newInstance(SModel sm, boolean init) {
    return (ConceptFunctionParameter_nodeToCopyPreProcess) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.lang.actions.structure.ConceptFunctionParameter_nodeToCopyPreProcess", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConceptFunctionParameter_nodeToCopyPreProcess newInstance(SModel sm) {
    return ConceptFunctionParameter_nodeToCopyPreProcess.newInstance(sm, false);
  }
}
