package jetbrains.mps.xmlQuery.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.builders.behavior.Builder_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class AttributeBuilder_BehaviorDescriptor extends Builder_BehaviorDescriptor {
  public AttributeBuilder_BehaviorDescriptor() {
  }

  public SNode virtual_getResultType_7057666463730718251(SNode thisNode) {
    return AttributeBuilder_Behavior.virtual_getResultType_7057666463730718251(thisNode);
  }

  public SNode virtual_getAttachStatementChild_4797501453850305563(SNode thisNode, SNode parentBuilder, SNode parentRef, SNode childRef) {
    return AttributeBuilder_Behavior.virtual_getAttachStatementChild_4797501453850305563(thisNode, parentBuilder, parentRef, childRef);
  }

  public SNode virtual_getCreatorExpression_7057666463730727863(SNode thisNode, SNode parentRef) {
    return AttributeBuilder_Behavior.virtual_getCreatorExpression_7057666463730727863(thisNode, parentRef);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.xmlQuery.structure.AttributeBuilder";
  }
}
