package jetbrains.mps.buildlanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.build.property.structure.PropertyNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ImportPropertyNode extends AbstractImportProperties implements IProjectComponent {
  public static final String concept = "jetbrains.mps.buildlanguage.structure.ImportPropertyNode";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String PROPERTY_NODE = "propertyNode";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public ImportPropertyNode(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ImportPropertyNode.NAME);
  }

  public void setName(String value) {
    this.setProperty(ImportPropertyNode.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ImportPropertyNode.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ImportPropertyNode.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ImportPropertyNode.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ImportPropertyNode.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ImportPropertyNode.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ImportPropertyNode.VIRTUAL_PACKAGE, value);
  }

  public PropertyNode getPropertyNode() {
    return (PropertyNode) this.getReferent(PropertyNode.class, ImportPropertyNode.PROPERTY_NODE);
  }

  public void setPropertyNode(PropertyNode node) {
    super.setReferent(ImportPropertyNode.PROPERTY_NODE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(ImportPropertyNode.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, ImportPropertyNode.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, ImportPropertyNode.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(ImportPropertyNode.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, ImportPropertyNode.SMODEL_ATTRIBUTE, node);
  }

  public static ImportPropertyNode newInstance(SModel sm, boolean init) {
    return (ImportPropertyNode) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.buildlanguage.structure.ImportPropertyNode", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ImportPropertyNode newInstance(SModel sm) {
    return ImportPropertyNode.newInstance(sm, false);
  }
}
