package jetbrains.mps.baseLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public abstract class AbstractStaticContainerProcessor implements IStaticContainerProcessor {
  protected SNode myStaticContainer;

  public AbstractStaticContainerProcessor(SNode staticContainer) {
    this.myStaticContainer = staticContainer;
  }

  public void addMethod(SNode method) {
    AbstractExtractMethodRefactoringProcessor.universalAddMethod(this.myStaticContainer, method);
  }
}
