package jetbrains.mps.baseLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IResolveInfo_BehaviorDescriptor;
import javax.swing.Icon;
import jetbrains.mps.smodel.SNode;
import java.util.List;

public class ConstructorDeclaration_BehaviorDescriptor extends BaseMethodDeclaration_BehaviorDescriptor implements ClassifierMember_BehaviorDescriptor, IResolveInfo_BehaviorDescriptor {
  public ConstructorDeclaration_BehaviorDescriptor() {
  }

  public Icon virtual_getAdditionalIcon_5017341185733863694(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_getAdditionalIcon_5017341185733863694(thisNode);
  }

  public String virtual_getPresentation_1213877396640(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_getPresentation_1213877396640(thisNode);
  }

  public List<SNode> virtual_getChildrenToDisplayIntention_4025276038182319200(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_getChildrenToDisplayIntention_4025276038182319200(thisNode);
  }

  public boolean virtual_canBeAnnotated_1233076312117(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_canBeAnnotated_1233076312117(thisNode);
  }

  public boolean virtual_isStatic_8986964027630462944(SNode thisNode) {
    return ClassifierMember_Behavior.virtual_isStatic_8986964027630462944(thisNode);
  }

  public boolean virtual_isReturnsVoid_1234359555698(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_isReturnsVoid_1234359555698(thisNode);
  }

  public boolean virtual_isDeprecated_1224609060727(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_isDeprecated_1224609060727(thisNode);
  }

  public String virtual_jniSignature_8847328628797656446(SNode thisNode) {
    return ConstructorDeclaration_Behavior.virtual_jniSignature_8847328628797656446(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.structure.ConstructorDeclaration";
  }
}
