package jetbrains.mps.baseLanguage.behavior;

/*Generated by MPS */


public class NotExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public NotExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.structure.NotExpression";
  }
}
