package jetbrains.mps.baseLanguage.behavior;

/*Generated by MPS */


public class NullType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor {
  public NullType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.structure.NullType";
  }
}
