package jetbrains.mps.baseLanguage.contracts.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Postcondition extends Condition {
  public static final String concept = "jetbrains.mps.baseLanguage.contracts.structure.Postcondition";

  public Postcondition(SNode node) {
    super(node);
  }

  public static Postcondition newInstance(SModel sm, boolean init) {
    return (Postcondition) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.contracts.structure.Postcondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Postcondition newInstance(SModel sm) {
    return Postcondition.newInstance(sm, false);
  }
}
