package jetbrains.mps.buildlanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Enum_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_toString_1213877413898(SNode thisNode) {
    StringBuffer sb = new StringBuffer();
    sb.append("{");
    for (int i = 0; i < ListSequence.fromList(SLinkOperations.getTargets(thisNode, "constants", true)).count(); i++) {
      sb.append(PropertyValueExpression_Behavior.call_toString_1213877472569(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "constants", true)).getElement(i)));
      if (i < ListSequence.fromList(SLinkOperations.getTargets(thisNode, "constants", true)).count() - 1) {
        sb.append(", ");
      }
    }
    sb.append("}");
    return sb.toString();
  }

  public static boolean call_inEnum_1213877413964(SNode thisNode, SNode nodeToCheck) {
    for (SNode constant : ListSequence.fromList(SLinkOperations.getTargets(thisNode, "constants", true))) {
      if (PropertyValueExpression_Behavior.call_toString_1213877472569(constant).equals(PropertyValueExpression_Behavior.call_toString_1213877472569(nodeToCheck))) {
        return true;
      }
    }
    return false;
  }
}
