package jetbrains.mps.lang.plugin.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;

public class ConceptFunctionParameter_DebuggableNode_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor {
  public ConceptFunctionParameter_DebuggableNode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.plugin.structure.ConceptFunctionParameter_DebuggableNode";
  }
}
