package jetbrains.mps.lang.plugin.behavior;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.smodel.SNode;

public interface IEnhancedRunConfiguration_BehaviorDescriptor {
  public List<SNode> virtual_getAdditionalParameters_3636700473138841189(SNode thisNode);
}
