package jetbrains.mps.nanoc.debug.answer;

/*Generated by MPS */


public abstract class GDBAnswer {
  protected char myTokenChar;

  public GDBAnswer(char tokenChar) {
    myTokenChar = tokenChar;
  }

  public char getTokenChar() {
    return myTokenChar;
  }
}
