package jetbrains.mps.lang.editor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.structure.structure.LinkDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CellModel_RefCell extends CellModel_WithRole {
  public static final String concept = "jetbrains.mps.lang.editor.structure.CellModel_RefCell";
  public static final String EDITOR_COMPONENT = "editorComponent";

  public CellModel_RefCell(SNode node) {
    super(node);
  }

  public LinkDeclaration getLinkDeclaration() {
    return this.ensureAdapter(LinkDeclaration.class, "relationDeclaration", this.getRelationDeclaration());
  }

  public void setLinkDeclaration(LinkDeclaration node) {
    this.setRelationDeclaration(node);
  }

  public InlineEditorComponent getEditorComponent() {
    return (InlineEditorComponent) this.getChild(InlineEditorComponent.class, CellModel_RefCell.EDITOR_COMPONENT);
  }

  public void setEditorComponent(InlineEditorComponent node) {
    super.setChild(CellModel_RefCell.EDITOR_COMPONENT, node);
  }

  public static CellModel_RefCell newInstance(SModel sm, boolean init) {
    return (CellModel_RefCell) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.lang.editor.structure.CellModel_RefCell", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CellModel_RefCell newInstance(SModel sm) {
    return CellModel_RefCell.newInstance(sm, false);
  }
}
