package jetbrains.mps.make.script.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class OptionExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public OptionExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.make.script.structure.OptionExpression";
  }
}
