package codeOrchestra.generator.listener;

/**
 * @author Alexander Eliseyev
 */
public enum GenerateEventType {
  PRE_GEN_SCRIPT_STARTED,
  PRE_GEN_SCRIPT_ENDED,

  GENERATION_STARTED,
  GENERATION_ENDED,

  PRIMARY_MAPPING_GENERATION_STARTED,
  PRIMARY_MAPPING_GENERATION_ENDED,

  SECONDARY_MAPPING_GENERATION_STARTED,
  SECONDARY_MAPPING_GENERATION_ENDED,

  POST_GEN_SCRIPT_STARTED,
  POST_GEN_SCRIPT_ENDED;
}
