package jetbrains.mps.gwt.client.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Source extends PatternFilter {
  public static final String concept = "jetbrains.mps.gwt.client.structure.Source";

  public Source(SNode node) {
    super(node);
  }

  public static Source newInstance(SModel sm, boolean init) {
    return (Source) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.gwt.client.structure.Source", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Source newInstance(SModel sm) {
    return Source.newInstance(sm, false);
  }
}
