package jetbrains.mps.lang.constraints.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class ConstraintFunction_RefSetHandlerKeepsReference_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public ConstraintFunction_RefSetHandlerKeepsReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.constraints.structure.ConstraintFunction_RefSetHandlerKeepsReference";
  }
}
