package jetbrains.mps.samples.agreementLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.samples.formulaLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EventVariableReference extends Expression {
  public static final String concept = "jetbrains.mps.samples.agreementLanguage.structure.EventVariableReference";
  public static final String EVENT_VARIABLE = "eventVariable";

  public EventVariableReference(SNode node) {
    super(node);
  }

  public EventVariable getEventVariable() {
    return (EventVariable) this.getReferent(EventVariable.class, EventVariableReference.EVENT_VARIABLE);
  }

  public void setEventVariable(EventVariable node) {
    super.setReferent(EventVariableReference.EVENT_VARIABLE, node);
  }

  public static EventVariableReference newInstance(SModel sm, boolean init) {
    return (EventVariableReference) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.samples.agreementLanguage.structure.EventVariableReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EventVariableReference newInstance(SModel sm) {
    return EventVariableReference.newInstance(sm, false);
  }
}
