package jetbrains.mps.lang.generator.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class GeneratorDescriptor_Behavior {
  public static void init(SNode thisNode) {
  }
}
