package jetbrains.mps.lang.generator.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class TemplateArgumentLinkPatternRefExpression_BehaviorDescriptor extends TemplateArgumentPatternRef_BehaviorDescriptor {
  public TemplateArgumentLinkPatternRefExpression_BehaviorDescriptor() {
  }

  public String virtual_getVariableName_2902001550281937661(SNode thisNode) {
    return TemplateArgumentLinkPatternRefExpression_Behavior.virtual_getVariableName_2902001550281937661(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.generator.structure.TemplateArgumentLinkPatternRefExpression";
  }
}
