package jetbrains.mps.lang.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class AddDependencyStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public AddDependencyStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.typesystem.structure.AddDependencyStatement";
  }
}
