package jetbrains.mps.lang.typesystem.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class OverloadedOpIsApplicableFunction_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public OverloadedOpIsApplicableFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.typesystem.structure.OverloadedOpIsApplicableFunction";
  }
}
