package jetbrains.mps.lang.test.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {
  public void install(DataFlowManager manager) {
    manager.register("jetbrains.mps.lang.test.structure.AssertMatch", new AssertMatch_DataFlow());
    manager.register("jetbrains.mps.lang.test.structure.EditorOperation", new EditorOperation_DataFlow());
    manager.register("jetbrains.mps.lang.test.structure.ExpressionContainer", new ExpressionContainer_DataFlow());
  }
}
