package jetbrains.mps.lang.pattern.behavior;

/*Generated by MPS */


public class AsPattern_BehaviorDescriptor extends PatternVariableDeclaration_BehaviorDescriptor {
  public AsPattern_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.pattern.structure.AsPattern";
  }
}
