package jetbrains.mps.baseLanguage.collections.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CustomMapCreator extends HashMapCreator {
  public static final String concept = "jetbrains.mps.baseLanguage.collections.structure.CustomMapCreator";
  public static final String CONTAINER_DECLARATION = "containerDeclaration";

  public CustomMapCreator(SNode node) {
    super(node);
  }

  public CustomContainerDeclaration getContainerDeclaration() {
    return (CustomContainerDeclaration) this.getReferent(CustomContainerDeclaration.class, CustomMapCreator.CONTAINER_DECLARATION);
  }

  public void setContainerDeclaration(CustomContainerDeclaration node) {
    super.setReferent(CustomMapCreator.CONTAINER_DECLARATION, node);
  }

  public static CustomMapCreator newInstance(SModel sm, boolean init) {
    return (CustomMapCreator) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.collections.structure.CustomMapCreator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CustomMapCreator newInstance(SModel sm) {
    return CustomMapCreator.newInstance(sm, false);
  }
}
