package jetbrains.mps.baseLanguage.collections.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LinkedListCreator extends AbstractContainerCreator {
  public static final String concept = "jetbrains.mps.baseLanguage.collections.structure.LinkedListCreator";

  public LinkedListCreator(SNode node) {
    super(node);
  }

  public static LinkedListCreator newInstance(SModel sm, boolean init) {
    return (LinkedListCreator) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.collections.structure.LinkedListCreator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LinkedListCreator newInstance(SModel sm) {
    return LinkedListCreator.newInstance(sm, false);
  }
}
