package jetbrains.mps.smodel.resources;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;
import jetbrains.mps.compiler.IClassesData;
import jetbrains.mps.make.resources.IResource;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

public class CResource extends MultiTuple._1<IClassesData> implements IResource, ICResouce {
  public CResource() {
    super();
  }

  public CResource(IClassesData classes) {
    super(classes);
  }

  public IClassesData classes(IClassesData value) {
    return super._0(value);
  }

  public IClassesData classes() {
    return super._0();
  }

  @SuppressWarnings(value = "unchecked")
  public CResource assignFrom(Tuples._1<IClassesData> from) {
    return (CResource) super.assign(from);
  }

  public String describe() {
    return null;
  }
}
